### ISSUE TITLE
חיבור אוטומטי

### ISSUE THREAD

**Issue by ns665869** [NetFree-Community/netfree-anywhere#6]
@magicode 
אולי צריך להוסיף השהיה בהפעלה של המחשב
או להוסיף נסיון חיבור נוסף לאחר כמה שניות
http://forum.netfree.link/topic/3354/%D7%97%D7%99%D7%91%D7%95%D7%A8-%D7%90%D7%95%D7%98%D7%95%D7%9E%D7%98%D7%99-%D7%A9%D7%9C-vpn/6

**Comment by magicode** [comment]
ברוך אומר ועושה.
